# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:6

before_script:
  - npm install

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test:lint:
  script:
    - npm install --dev
    - npm run lint

test:vulnerabilities:
  script:
    - npm audit

# Supported node versions can be found here:
# https://github.com/nodejs/LTS#lts_schedule
# jest does not support node < 4
# https://facebook.github.io/jest/docs/troubleshooting.html#compatibility-issues
test:node:10:
  image: node:10
  script:
    - npm install -g codecov
    - npm test && codecov

test:node:8:
  image: node:8
  script:
    # - npm run build
    - npm test


# Publish tagged versions to npm
publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    # - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish